defaultRules:
  rules:
    kubeSchedulerAlerting: false
    kubeProxy: false
    kubeControllerManager: false

kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false

prometheus:
  networkPolicy:
    enabled: true
  prometheusSpec:
    replicas: 1
    resources:
      requests:
        memory: 2Gi
        cpu: 250m
      limits:
        memory: 2Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: nephtek-com-issuer
    hosts:
      - prometheus.k8s.nephtek.com
    tls:
      - secretName: prometheus-k8s-nephtek-com-cert
        hosts:
          - prometheus.k8s.nephtek.com

prometheusOperator:
  networkPolicy:
    enabled: true
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi

grafana:
  additionalDataSources:
    - name: Loki
      url: http://loki-gateway.logging.svc.cluster.local
      type: loki
    - name: Tempo
      url: http://tempo.tempo:3100
      type: tempo
  monitoring:
    rules:
      labels:
        release: kube-prometheus-stack
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  sidecar:
    resources:
      limits:
        memory: 120Mi
      requests:
        cpu: 10m
        memory: 90Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: nephtek-com-issuer
    hosts:
      - grafana.k8s.nephtek.com
    tls:
      - secretName: grafana-k8s-nephtek-com-cert
        hosts:
          - grafana.k8s.nephtek.com

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
        memory: 160Mi
