apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-promtail-minikube
    files:
      - values.promtail.minikube.yaml
resources:
  - ../base
patches:
  - path: patch-promtail-helm-release.yaml
