apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-opentelemetry-docker-desktop
      valuesKey: values.docker-desktop.yaml
