apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-bench
  namespace: kube-bench
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-bench
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: kube-bench
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
