apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-tempo-docker-desktop
      valuesKey: values.docker-desktop.yaml
