persistence:
  enabled: true
  storageClassName: local-path
tempo:
  resources:
    requests:
      cpu: 10m
      memory: 120Mi
    limits:
      memory: 200Mi
tempoQuery:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: nephtek-com-issuer
    enabled: true
    hosts:
      - tempo.k8s.nephtek.com
    ingressClassName: nginx
    tls:
      - hosts:
          - tempo.k8s.nephtek.com
        secretName: tempo-k8s-nephtek-com-cert
