persistence:
  enabled: true
  storageClassName: hostpath
tempo:
  resources:
    requests:
      cpu: 10m
      memory: 1000Mi
    limits:
      memory: 2000Mi
tempoQuery:
  service:
    port: 4318
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: nephtek-com-issuer
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    enabled: true
    hosts:
      - tempo.k8s.nephtek.com
    ingressClassName: nginx
    tls:
      - hosts:
          - tempo.k8s.nephtek.com
        secretName: tempo-k8s-nephtek-com-cert
