apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-loki-minikube
    files:
      - values.loki.minikube.yaml
resources:
  - ../base
patches:
  - path: patch-loki-helm-release.yaml
