apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-loki-kind
      valuesKey: values.loki.kind.yaml
