apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 120m0s
  url: https://kubernetes-sigs.github.io/metrics-server/
