loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 375Mi
    limits:
      memory: 750Mi
monitoring:
  serviceMonitor:
    labels:
      release: kube-prometheus-stack
rbac:
  pspEnabled: false
ingress:
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: nephtek-com-issuer
  hosts:
    - loki.k8s.nephtek.com
  tls:
    - hosts:
        - loki.k8s.nephtek.com
      secretName: loki-k8s-nephtek-com-cert
