resources:
  limits:
    memory: 14Mi
  requests:
    cpu: 100m
    memory: 140Mi
config:
  clients:
    - url: http://loki-gateway/loki/api/v1/push
      tenant_id: 1
serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
networkPolicy:
  enabled: true
