apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-k8s-nephtek-com-cert
  namespace: keycloak
spec:
  dnsNames:
  - keycloak.k8s.nephtek.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: nephtek-com-issuer
  secretName: keycloak-k8s-nephtek-com-cert
  usages:
  - digital signature
  - key encipherment
