apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  resources:
    requests:
      cpu: 10m
      memory: 175Mi
    limits:
      memory: 512Mi
  ingress:
    enabled: false
    className: nginx
  db:
    vendor: postgres
    host: pg-keycloak-rw
    usernameSecret:
      name: pg-keycloak-app
      key: username
    passwordSecret:
      name: pg-keycloak-app
      key: password
  http:
    httpEnabled: true
  hostname:
    strict: false
    hostname: keycloak.k8s.nephtek.com
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  unsupported:
    podTemplate:
      spec:
        containers:
        - name: keycloak
          env:
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "false"
