apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-keycloak
spec:
  instances: 1
  resources:
    requests:
      cpu: 10m
      memory: 175Mi
    limits:
      memory: 512Mi
  bootstrap:
    initdb:
      database: keycloak
  storage:
    size: 8Gi
  affinity:
    topologyKey: topology.kubernetes.io/zone
  priorityClassName:
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  logLevel: info
  enableSuperuserAccess: true
  superuserSecret:
  postgresql:
    shared_preload_libraries:
  monitoring:
    enablePodMonitor: false
  backup:
