apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-promtail-kind
      valuesKey: values.promtail.kind.yaml
