apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
spec:
  interval: 1m
  chart:
    spec:
      chart: backstage
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: backstage
        namespace: backstage
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
