apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-metrics-server-docker-desktop
    files:
      - values.metrics-server.docker-desktop.yaml
resources:
  - ../base
patches:
  - path: patch-metrics-server-helm-release.yaml
