apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 1m
  chart:
    spec:
      chart: metallb
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
