extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53
installCRDs: true
podDnsConfig:
  nameservers:
    - 8.8.8.8
podDnsPolicy: None
resources:
  requests:
    cpu: 20m
    memory: 50Mi
  limits:
    memory: 75Mi
webhook:
  networkPolicy:
    enabled: true
