apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-weave-gitops-rancher-desktop
      valuesKey: values.rancher-desktop.yaml
