apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-ingress-nginx-kind
    files:
      - values.kind.yaml
resources:
  - ../base
patches:
  - path: patch-helm-release.yaml
