apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-metallb-kind
    files:
      - values.metallb.kind.yaml
resources:
  - ../base
patches:
  - path: patch-metallb-helm-release.yaml
