prometheus:
  serviceAccount: kube-prometheus-stack-prometheus
  namespace: monitoring
  podMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
  serviceMonitor:
    enabled: true
    speaker:
      additionalLabels:
        release: kube-prometheus-stack
    controller:
      additionalLabels:
        release: kube-prometheus-stack
  prometheusRule:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
controller:
  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 50Mi
speaker:
  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 50Mi
