apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: opentelemetry
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
