apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-backstage-rancher-desktop
    files:
      - values.rancher-desktop.yaml
resources:
  - ../base
  - pg-cluster.yaml
patches:
  - path: patch-helm-release.yaml
