apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-backstage-rancher-desktop
      valuesKey: values.rancher-desktop.yaml
